"""
Reports — generate CSV exports from the trade log.

UAE-tax-CSV columns are chosen to be useful both for personal record-keeping
(if the FTA ever asks) and for handover to a UAE accountant. They aren't a
mandated format — FTA hasn't published one for crypto.

Output columns:
  date, exchange, pair, side, amount_aed, amount_btc,
  price_aed_per_btc, fee_aed, source_doc_id

Plus summary block at the bottom with totals.
"""
from __future__ import annotations

import csv
import logging
from datetime import datetime, timedelta, timezone
from decimal import Decimal
from pathlib import Path
from typing import Optional

from bitcoiners_dca.persistence.db import Database

logger = logging.getLogger(__name__)


def export_uae_tax_csv(
    db: Database,
    out_dir: str | Path,
    year: Optional[int] = None,
) -> Path:
    """Write a YYYY.csv to out_dir summarizing all trades that year.

    If year is None, exports lifetime.

    Returns the path written.
    """
    out_path = Path(out_dir)
    out_path.mkdir(parents=True, exist_ok=True)

    if year:
        start = datetime(year, 1, 1)
        end = datetime(year + 1, 1, 1)
        filename = f"bitcoiners-dca-trades-{year}.csv"
    else:
        start = datetime(1970, 1, 1)
        end = datetime.now(timezone.utc) + timedelta(days=1)
        filename = "bitcoiners-dca-trades-lifetime.csv"

    file_path = out_path / filename

    # Pull rows from SQLite directly — easier than reconstructing Pydantic models
    rows = db._conn.execute(
        """SELECT timestamp, exchange, order_id, pair, side,
                  amount_quote, amount_base, price_avg, fee_quote
           FROM trades
           WHERE timestamp >= ? AND timestamp < ?
           ORDER BY timestamp ASC""",
        (start.isoformat(), end.isoformat()),
    ).fetchall()

    total_aed = Decimal(0)
    total_btc = Decimal(0)
    total_fees = Decimal(0)

    with file_path.open("w", newline="") as f:
        writer = csv.writer(f)
        writer.writerow(
            [
                "Date",
                "Exchange",
                "Pair",
                "Side",
                "Amount (AED)",
                "Amount (BTC)",
                "Price (AED per BTC)",
                "Fee (AED)",
                "Order ID",
            ]
        )

        for row in rows:
            ts_str = row["timestamp"].split("T")[0]
            amount_aed = Decimal(str(row["amount_quote"] or 0))
            amount_btc = Decimal(str(row["amount_base"] or 0))
            price = Decimal(str(row["price_avg"] or 0))
            fee = Decimal(str(row["fee_quote"] or 0))

            writer.writerow(
                [
                    ts_str,
                    row["exchange"],
                    row["pair"],
                    row["side"],
                    f"{amount_aed:.2f}",
                    f"{amount_btc:.8f}",
                    f"{price:.2f}",
                    f"{fee:.2f}",
                    row["order_id"],
                ]
            )

            if row["side"] == "buy":
                # Only the AED-quoted legs count toward "AED spent" —
                # otherwise multi-hop cycles double-count (AED→USDT→BTC
                # contributes both the AED outlay AND the USDT amount-as-
                # AED). Only the BTC-receiving legs count toward "BTC
                # acquired" — otherwise USDT amount_base values get
                # summed in as if they were BTC, yielding nonsense like
                # 1003 "BTC" from 12 cycles. Fees are AED-equivalent so
                # we only sum the AED-quoted ones to avoid mixing USDT
                # fees in. This matches Database.total_btc_bought /
                # total_aed_spent semantics; see also btc_cost_basis_aed
                # for the weighted-USDT-rate cost-basis calculation.
                pair = str(row["pair"] or "")
                if pair.endswith("/AED"):
                    total_aed += amount_aed
                    total_fees += fee
                if pair.startswith("BTC/"):
                    total_btc += amount_btc

        # Summary section
        writer.writerow([])
        writer.writerow(["=== SUMMARY ==="])
        writer.writerow(["Total AED spent (buys)", f"{total_aed:.2f}"])
        writer.writerow(["Total BTC acquired", f"{total_btc:.8f}"])
        writer.writerow(["Total fees (AED)", f"{total_fees:.2f}"])
        if total_btc > 0:
            avg_price = total_aed / total_btc
            writer.writerow(["Average price (AED/BTC)", f"{avg_price:.2f}"])
        writer.writerow([])
        writer.writerow(
            [
                "Generated by bitcoiners-dca on",
                datetime.now(timezone.utc).isoformat(),
            ]
        )
        writer.writerow(
            [
                "UAE personal Bitcoin gains are not taxed.",
                "This report is for personal record-keeping.",
            ]
        )

    logger.info("Wrote %s", file_path)
    return file_path
